### ISSUE TITLE
Roundtime not changing

### ISSUE THREAD

**Issue by criskkky** [oqyh/cs2-Map-Configs-GoldKingZ#1]
`mp_roundtime 20` isn't working on this map
https://steamcommunity.com/sharedfiles/filedetails/?id=3072637092

**Comment by oqyh** [comment]
add
`mp_warmup_end`
top of the prefix cfg
example:
```
sv_cheats 0
mp_roundtime 20
```
to 
```
mp_warmup_end
sv_cheats 0
mp_roundtime 20
```

**Comment by criskkky** [comment]
@oqyh I made the change you requested but nothing happens,
Maybe it's a problem related to map 'cos in other workshop maps i don't have that issue 🤔

**Comment by oqyh** [comment]
will check that

**Comment by criskkky** [comment]
@oqyh FOUND A SOLUTION, the problem was `mp_roundtime_defuse`
> Source: https://steamcommunity.com/app/730/discussions/0/864976115799006407/

**Comment by oqyh** [comment]
yes you need to check together to change top timer

mp_roundtime_defuse
mp_roundtime
