### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by criskkky** [oqyh/cs2-Map-Configs-GoldKingZ#2]
Hi, I was checking your plugin, and I noticed that is repeating the applying process if server is empty (endless)
and I'm getting CPU% spikes on my server due of that.

Could be better if you just use `EventRoundAnnounceMatchStart` & `EventRoundAnnounceWarmup`?

**Comment by criskkky** [comment]
It **only** happens when server is empty btw

**Comment by oqyh** [comment]
plugin will execute  ((one time))  couple of event to make sure  there is no value changed

some of maps creator hide cvars in Onmapstart and some of them in EventRoundAnnounceWarmup and some of them EventRoundAnnounceMatchStart 

make sure sv_hibernate_when_empty false
its not plugin

**Comment by criskkky** [comment]
Ty!
