### ISSUE TITLE
Timers causing problems (maybe)

### ISSUE THREAD

**Issue by criskkky** [oqyh/cs2-Map-Configs-GoldKingZ#3]
**Demo:**
![image](https://github.com/oqyh/cs2-Map-Configs-Prefix/assets/36176343/1f0ea3e5-ad85-49d5-b935-a8c26136531d)

Hi @oqyh,
I have a problem on my server related to this cvar, `mp_equipment_reset_rounds`.

Sequence:
1. At mapstart (or first round) everything is ok.
2. At second round cvars are applied with delay (like 1s), I discovered it spamming console cvar, that allows me get current value applied to that cvar as I showed in demo image.

I think it's 'cos `mp_equipment_reset_rounds` is set at `0` as default config in this workshop map. So that's why only have problems with this cvar, but could have more problems with other cvars if that were setted as default in the config of the workshop map.

So, as solution, I think that you could provide a manual setting for timer through json file. Or set the first config call without a timer.

Why I think that's related to timers?
That's 'cos I tested [CS2Jailbreak](https://github.com/destoer/Cs2Jailbreak) this plugin is without timers related to cvar applying and `mp_equipment_reset_rounds` doesn't have that delay problem.

I hope you understand the proposed logic, if there is something I left out or was not understood, let me know.

**Comment by oqyh** [comment]
hello criskkky,

prefix plugin execute config path > (1) - on map start > (2) - warmup > (3) - Matchstart > plugin will not execute means plugin will stop 


Cs2Jailbreak execute config path > looping on every roundstart > result override prefix plugin on second round
https://github.com/destoer/Cs2Jailbreak/blob/f831c15075df54690b55919e2aee9c173f807283/src/Jail.cs#L484

solution: i will make update to modify your needs

**Comment by criskkky** [comment]
ty broo, I'm tuned

**Comment by oqyh** [comment]
> ty broo, I'm tuned

sorry for delay i just i was working on other project 
here is my last update 



```
{
  //-----------Event Calls Path-----------//
  //-------------------------------------//
  //OnMapStart: Will Be Called On Map Start 1 Time Only
  //OnWarmupStart: Will Be Called On WarmUp Only
  //OnRoundStart: Will Be Called On Every Round Start Include WarmUp
  //OnMatchStart: Will Be Called On Match Started (Round 1) 1 Time Only
  //OnPlayerSpawn: Will Be Called On Every Player Spawn
  //-------------------------------------//
  
//-----------------------------------------------------------------------------------------

  //This On Normal Cfg example de_.cfg or de_dust2.cfg or _default_.cfg
  "ExecMode": "OnMapStart,OnWarmupStart,OnRoundStart,OnMatchStart",
  "ExecXTimes": 3,
  
//-----------------------------------------------------------------------------------------

  //This On Force Cfg example f_de_.cfg or f_de_dust2.cfg
  "ForceExecMode": "OnPlayerSpawn",
  "ForceExecXTimes": 1,
  
//-----------------------------------------------------------------------------------------

  "EnableErrorLogChecker": false,
//-----------------------------------------------------------------------------------------

  "ConfigVersion": 1
}
```

if you have anything to add or ideas ill take it for now this will must be better

**Comment by criskkky** [comment]
@oqyh don't worry bro <3
I was thinking on a json like this, but idk if you could do it:

```json
{
    // ----------------------------------------------------------
    // Simple true or false values to enable/disable the plugin on certain events.

    "ExecOnMapStart": true,
    "ExecOnWarmupStart": true,
    "ExecOnRoundStart": true,
    "ExecOnMatchStart": true,
    "ExecXTimes": 3,
    
    // ----------------------------------------------------------
    // This forces the plugin to execute the commands without requiring "f_de_" .cfg files

    "ForcedPrefixesOrMaps": [
        "jb_",
        "de_",
        "de_dust2"
    ],

    // ----------------------------------------------------------
    // Simple true or false values to enable/disable the plugin on certain events to specified maps on "ForcedPrefixesOrMaps".

    "ForceOnMapStart": false,
    "ForceOnWarmupStart": false,
    "ForceOnRoundStart": false,
    "ForceOnMatchStart": false,
    "ForceXTimes": 1,

    "EnableErrorLogChecker": false,

    "ConfigVersion": 1
}
```

**Comment by oqyh** [comment]
that exactly what i did

now you have 2 saparet cfg with saparet events

in prefixcfg

de_dust2.cfg
surf_.cfg
they are exec on only these 
  "ExecMode": "OnMapStart,OnWarmupStart,OnRoundStart,OnMatchStart",
  "ExecXTimes": 3,

=====================================================
and
f_de_dust2.cfg
f_surf_.cfg
they are exec on only these 
  "ForceExecMode": "OnPlayerSpawn",
  "ForceExecXTimes": 1,
  
  ====================================================
  
  and once you put 
  OnPlayerSpawn it will Exec ExecMode or ForceExecMode depend what you put in it
  if you want to add more just add , and the event
  and these are event available

```
  //-----------Event Calls Path-----------//
  //-------------------------------------//
  //OnMapStart: Will Be Called On Map Start 1 Time Only
  //OnWarmupStart: Will Be Called On WarmUp Only
  //OnRoundStart: Will Be Called On Every Round Start Include WarmUp
  //OnMatchStart: Will Be Called On Match Started (Round 1) 1 Time Only
  //OnPlayerSpawn: Will Be Called On Every Player Spawn
  //-------------------------------------//
  ```

**Comment by criskkky** [comment]
Hi @oqyh, my bad, previously I showed a case where "f_file" weren't necessary, but with that "f_file" we can add just the commands that are causing conflicts, i didn't thought about that. Forget my previous json.

According to yours, an improvement could look like this:

### Events Call:

```
Listeners.OnMapStart => OnMapStart
EventRoundAnnounceWarmup => OnWarmupStart
EventRoundPrestart => OnRoundPrestart
EventRoundStart => OnRoundStart
EventRoundPoststart => OnRoundPoststart
EventRoundEnd => OnRoundEnd
EventRoundOfficiallyEnded => OnRoundOfficiallyEnded
```

### Where we can define:
How many times we can execute our cfgs on each event.
In your code you are using "AddTimer" so would be great be able to modify that from config too.

Based on previous text, new `Map_Configs_Prefix.json` would looks like this

```json
{
  //----------- Event Calls Path -----------//
  // For normal files.

  // Listeners.OnMapStart => OnMapStart
  // EventRoundAnnounceWarmup => OnWarmupStart
  // EventRoundPrestart => OnRoundPrestart
  // EventRoundStart => OnRoundStart
  // EventRoundPoststart => OnRoundPoststart
  // EventRoundEnd => OnRoundEnd
  // EventRoundOfficiallyEnded => OnRoundOfficiallyEnded

//----------------------------------------------------------------------//

  // This is for normal cfg; example: de_.cfg | de_dust2.cfg | _default_.cfg

  "ExecMode": "OnMapStart, OnWarmupStart, OnRoundPrestart, OnRoundStart",
  "ExecModeXTimes": 1,
  "TimerBetweenExecMode": 0.1, // In Milseconds

//----------------------------------------------------------------------//

  // This is for forced cfg; example: f_de_.cfg | f_de_dust2.cfg | f_default_.cfg

  "ForcedExecMode": "OnRoundStart, OnRoundPoststart, OnRoundPoststart, OnRoundEnd, OnRoundOfficiallyEnded",
  "ForcedExecModeXTimes": 2,
  "ForcedTimerBetweenExecMode": 0.0, // In Milseconds

//----------------------------------------------------------------------//

  "EnableErrorLogChecker": false,
//----------------------------------------------------------------------//

  "ConfigVersion": 2
}
```

**Comment by oqyh** [comment]
YES

> Hi @oqyh, my bad, previously I showed a case where "f_file" weren't necessary, but with that "f_file" we can add just the commands that are causing conflicts, i didn't thought about that. Forget my previous json.
> 
> According to yours, an improvement could look like this:
> 
> ### Events Call:
> ```
> Listeners.OnMapStart => OnMapStart
> EventRoundAnnounceWarmup => OnWarmupStart
> EventRoundPrestart => OnRoundPrestart
> EventRoundStart => OnRoundStart
> EventRoundPoststart => OnRoundPoststart
> EventRoundEnd => OnRoundEnd
> EventRoundOfficiallyEnded => OnRoundOfficiallyEnded
> ```
> 
> ### Where we can define:
> How many times we can execute our cfgs on each event. In your code you are using "AddTimer" so would be great be able to modify that from config too.
> 
> Based on previous text, new `Map_Configs_Prefix.json` would looks like this
> 
> ```json
> {
>   //----------- Event Calls Path -----------//
>   // For normal files.
> 
>   // Listeners.OnMapStart => OnMapStart
>   // EventRoundAnnounceWarmup => OnWarmupStart
>   // EventRoundPrestart => OnRoundPrestart
>   // EventRoundStart => OnRoundStart
>   // EventRoundPoststart => OnRoundPoststart
>   // EventRoundEnd => OnRoundEnd
>   // EventRoundOfficiallyEnded => OnRoundOfficiallyEnded
> 
> //----------------------------------------------------------------------//
> 
>   // This is for normal cfg; example: de_.cfg | de_dust2.cfg | _default_.cfg
> 
>   "ExecMode": "OnMapStart, OnWarmupStart, OnRoundPrestart, OnRoundStart",
>   "ExecModeXTimes": 1,
>   "TimerBetweenExecMode": 0.1, // In Milseconds
> 
> //----------------------------------------------------------------------//
> 
>   // This is for forced cfg; example: f_de_.cfg | f_de_dust2.cfg | f_default_.cfg
> 
>   "ForcedExecMode": "OnRoundStart, OnRoundPoststart, OnRoundPoststart, OnRoundEnd, OnRoundOfficiallyEnded",
>   "ForcedExecModeXTimes": 2,
>   "ForcedTimerBetweenExecMode": 0.0, // In Milseconds
> 
> //----------------------------------------------------------------------//
> 
>   "EnableErrorLogChecker": false,
> //----------------------------------------------------------------------//
> 
>   "ConfigVersion": 2
> }
> ```

yes AddTimer is editable its ExecModeXTimes/ForcedExecModeXTimes
lets say ExecModeXTimes 2
will be exec cfg 2 times

**Comment by oqyh** [comment]
ill update couple mins give it try

**Comment by oqyh** [comment]
Done

**Comment by criskkky** [comment]
Hi @oqyh, with new update i'm using this config:

```json
// This configuration was automatically generated by CounterStrikeSharp for plugin 'Map_Configs_Prefix', at 2024/01/28 07:53:10
{
  "ExecMode": "OnRoundStart,OnMapStart,OnMatchStart,OnWarmupStart",
  "ExecXTimes": 1,
  "ForceExecMode": "OnPlayerSpawn",
  "ForceExecXTimes": 0,
  "EnableErrorLogChecker": false,
  "ConfigVersion": 1
}
```

Currently everything is ok **without** using "ForceExecMode", the thing isn't how many times you execute the config is how fast after each round event :wink:.
With new timers you defined plugin allows correctly apply the configs.

**Comment by oqyh** [comment]
perfect 

> Hi @oqyh, with new update i'm using this config:
> 
> ```json
> // This configuration was automatically generated by CounterStrikeSharp for plugin 'Map_Configs_Prefix', at 2024/01/28 07:53:10
> {
>   "ExecMode": "OnRoundStart,OnMapStart,OnMatchStart,OnWarmupStart",
>   "ExecXTimes": 1,
>   "ForceExecMode": "OnPlayerSpawn",
>   "ForceExecXTimes": 0,
>   "EnableErrorLogChecker": false,
>   "ConfigVersion": 1
> }
> ```
> 
> Currently everything is ok **without** using "ForceExecMode", the thing isn't how many times you execute the config is how fast after each round event 😉. With new timers you defined plugin allows correctly apply the configs.

perfect glad it help what you need keep in mind made it open to for future problems here is what i ment 


sometimes map creator or plugin loop in sv_cheats 1 and you dont want that on old update you have 1 config 

surf_.cfg
inside it 
mp_timelimit 5
and sv_cheats 0 
if map creator or plugin creator made convar sv_cheats 1 on every round that will be no use because its gonna loop on everyround 
if i added on everyround loop its gonna loop mp_timelimit 5 on everyround making it possible it use it 

so in new update you put 
inside surf_.cfg
mp_timelimt 5 on match start and not on everyround 
inside f_surf_.cfg
sv_cheats 0 on everyround start with timer 2 making it impossible to change 

anyways glad it helps
goodluck🫡

**Comment by criskkky** [comment]
Any problem I tell u, tysm!
