### ISSUE TITLE
[Enhancement]: Invert how plugin analyzes each map config

### ISSUE THREAD

**Issue by criskkky** [oqyh/cs2-Map-Configs-GoldKingZ#5]
Hi @oqyh, (idk if next enhancement it's possible)

> **README.MD:**
>・if plugin cannot find (surf_.cfg) will start search to full map name config (surf_boreas.cfg).
>・if plugin cannot find (surf_boreas.cfg) will execute (_default_.cfg).

The instructions in the `README.MD` file specify that the plugin first analyzes the map prefix and then looks for a specific configuration for that map. However, it would be more logical to invert this process. Consider a scenario where there are many maps with the "aim_" prefix, and the need arises to configure specific settings for certain maps, such as aim_deagle and aim_awp. In this case, it would be more practical for the plugin to first search for full map name, then part of map name and then analyze the map prefix if specific configuration wasn't found.

* With "specific config" I mean => aim_deagle_lego.cfg
* With "map prefix config" I mean => aim_.cfg

So in resume the new scan should be in this order:
1. aim_deagle_lego.cfg => full map.
2. aim_deagle_.cfg => part of map name.
3. aim_.cfg => just prefix.
4. _default_.cfg => default if previous wasn't found.

**Comment by oqyh** [comment]
> Hi @oqyh, (idk if next enhancement it's possible)
> 
> > **README.MD:**
> > ・if plugin cannot find (surf_.cfg) will start search to full map name config (surf_boreas.cfg).
> > ・if plugin cannot find (surf_boreas.cfg) will execute (_default_.cfg).
> 
> The instructions in the `README.MD` file specify that the plugin first analyzes the map prefix and then looks for a specific configuration for that map. However, it would be more logical to invert this process. Consider a scenario where there are many maps with the "aim_" prefix, and the need arises to configure specific settings for certain maps, such as aim_deagle and aim_awp. In this case, it would be more practical for the plugin to first search for full map name, then part of map name and then analyze the map prefix if specific configuration wasn't found.
> 
> * With "specific config" I mean => aim_deagle_lego.cfg
> * With "map prefix config" I mean => aim_.cfg
> 
> So in resume the new scan should be in this order:
> 
> 1. aim_deagle_lego.cfg => full map.
> 2. aim_deagle_.cfg => part of map name.
> 3. aim_.cfg => just prefix.
> 4. _default_.cfg => default if previous wasn't found.

hi @criskkky 

i can make invert  mode but this better way

**Comment by oqyh** [comment]
done
